# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-7acc3601be8248e69b9c3ffd1b0d98f5
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-7acc3601be8248e69b9c3ffd1b0d98f5
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
cos:
  client:
    host: https://positive-ai-code-1328260883.cos.ap-nanjing.myqcloud.com
    secretId: AKIDsjPs8B0bzHLBoDOL4at1w6KQLIC0e7OS
    secretKey: tZ5QXQ9h3CAvSt8AyYu2zjIwNaZMwLZZ
    region: ap-nanjing
    bucket: positive-ai-code-1328260883