spring:
  application:
    name: positive-ai-code-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/positive_ai_code?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 628965
  profiles:
    active: local
server:
  port: 8080
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.xr.positiveaicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
